name = "mail-portal"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DOMAIN = "sheer.biz.id"
APP_BASE_URL = "https://portal.sheer.biz.id"
DEFAULT_ALIAS_LIMIT = "3"
SESSION_TTL_SECONDS = "1209600"
RESET_TTL_SECONDS = "3600"

[[d1_databases]]
binding = "DB"
database_name = "mail_portal"
database_id = "a78e8ca1-b274-46dd-b84f-f8a9c838f733"
